spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ccs
    url: jdbc:mysql://ccsyasu.cafe24.com:3306/ccsyasu_db
    password: ccsYasu

server:
  servlet:
    encoding:
      force-response: 'true'
    session:
      timeout: 30m
  port: 8081